// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MT.SAP.CRM
{
	public partial class LoginTableViewController : UITableViewController
	{
		public LoginTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
