//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.CRM.Gateway.SAPServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SAPServiceReference.ZIGNMOBILESALESACTIVITY")]
    public interface ZIGNMOBILESALESACTIVITY {
        
        // CODEGEN: Generating message contract since the operation ZIgnBpcontactGetlist is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1 ZIgnBpcontactGetlist(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1> ZIgnBpcontactGetlistAsync(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZIgnBpcontactGetlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerField;
        
        private int daysBackwardField;
        
        private bool daysBackwardFieldSpecified;
        
        private int daysForwardField;
        
        private bool daysForwardFieldSpecified;
        
        private string myCustomersField;
        
        private string mySalesActivityField;
        
        private Rangesktast[] statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int DaysBackward {
            get {
                return this.daysBackwardField;
            }
            set {
                this.daysBackwardField = value;
                this.RaisePropertyChanged("DaysBackward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysBackwardSpecified {
            get {
                return this.daysBackwardFieldSpecified;
            }
            set {
                this.daysBackwardFieldSpecified = value;
                this.RaisePropertyChanged("DaysBackwardSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int DaysForward {
            get {
                return this.daysForwardField;
            }
            set {
                this.daysForwardField = value;
                this.RaisePropertyChanged("DaysForward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysForwardSpecified {
            get {
                return this.daysForwardFieldSpecified;
            }
            set {
                this.daysForwardFieldSpecified = value;
                this.RaisePropertyChanged("DaysForwardSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MyCustomers {
            get {
                return this.myCustomersField;
            }
            set {
                this.myCustomersField = value;
                this.RaisePropertyChanged("MyCustomers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MySalesActivity {
            get {
                return this.mySalesActivityField;
            }
            set {
                this.mySalesActivityField = value;
                this.RaisePropertyChanged("MySalesActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Rangesktast[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Rangesktast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signField;
        
        private string optionField;
        
        private string lowField;
        
        private string highField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("Sign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("Option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
                this.RaisePropertyChanged("Low");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
                this.RaisePropertyChanged("High");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class VbkaTlinekom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refobjecttypeField;
        
        private string refobjectkeyField;
        
        private string docNumberField;
        
        private string textIdField;
        
        private string languField;
        
        private string langupIsoField;
        
        private string textLineField;
        
        private string functionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Refobjecttype {
            get {
                return this.refobjecttypeField;
            }
            set {
                this.refobjecttypeField = value;
                this.RaisePropertyChanged("Refobjecttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Refobjectkey {
            get {
                return this.refobjectkeyField;
            }
            set {
                this.refobjectkeyField = value;
                this.RaisePropertyChanged("Refobjectkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocNumber {
            get {
                return this.docNumberField;
            }
            set {
                this.docNumberField = value;
                this.RaisePropertyChanged("DocNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TextId {
            get {
                return this.textIdField;
            }
            set {
                this.textIdField = value;
                this.RaisePropertyChanged("TextId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Langu {
            get {
                return this.languField;
            }
            set {
                this.languField = value;
                this.RaisePropertyChanged("Langu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LangupIso {
            get {
                return this.langupIsoField;
            }
            set {
                this.langupIsoField = value;
                this.RaisePropertyChanged("LangupIso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TextLine {
            get {
                return this.textLineField;
            }
            set {
                this.textLineField = value;
                this.RaisePropertyChanged("TextLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
                this.RaisePropertyChanged("Function");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bus1037VbkakomCr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refobjecttypeField;
        
        private string refobjectkeyField;
        
        private string docNumberField;
        
        private string refdoctypeField;
        
        private string refreltypeField;
        
        private string activityTypeField;
        
        private string salesorgField;
        
        private string distrChanField;
        
        private string divisionField;
        
        private string salesOffField;
        
        private string salesGrpField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string fromTimeField;
        
        private string toTimeField;
        
        private string reasonField;
        
        private string resultField;
        
        private string resultExplanationField;
        
        private string stateField;
        
        private string followUpTypeField;
        
        private string followUpDateField;
        
        private string activityCommentField;
        
        private string descrpt01Field;
        
        private string descrpt02Field;
        
        private string descrpt03Field;
        
        private string descrpt04Field;
        
        private string descrpt05Field;
        
        private string descrpt06Field;
        
        private string descrpt07Field;
        
        private string descrpt08Field;
        
        private string descrpt09Field;
        
        private string descrpt10Field;
        
        private string txtKonseField;
        
        private string directionField;
        
        private string partnRoleField;
        
        private string partnIdField;
        
        private string contactRoleField;
        
        private string contactField;
        
        private string languField;
        
        private string languIsoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Refobjecttype {
            get {
                return this.refobjecttypeField;
            }
            set {
                this.refobjecttypeField = value;
                this.RaisePropertyChanged("Refobjecttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Refobjectkey {
            get {
                return this.refobjectkeyField;
            }
            set {
                this.refobjectkeyField = value;
                this.RaisePropertyChanged("Refobjectkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocNumber {
            get {
                return this.docNumberField;
            }
            set {
                this.docNumberField = value;
                this.RaisePropertyChanged("DocNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Refdoctype {
            get {
                return this.refdoctypeField;
            }
            set {
                this.refdoctypeField = value;
                this.RaisePropertyChanged("Refdoctype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Refreltype {
            get {
                return this.refreltypeField;
            }
            set {
                this.refreltypeField = value;
                this.RaisePropertyChanged("Refreltype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ActivityType {
            get {
                return this.activityTypeField;
            }
            set {
                this.activityTypeField = value;
                this.RaisePropertyChanged("ActivityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Salesorg {
            get {
                return this.salesorgField;
            }
            set {
                this.salesorgField = value;
                this.RaisePropertyChanged("Salesorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DistrChan {
            get {
                return this.distrChanField;
            }
            set {
                this.distrChanField = value;
                this.RaisePropertyChanged("DistrChan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SalesOff {
            get {
                return this.salesOffField;
            }
            set {
                this.salesOffField = value;
                this.RaisePropertyChanged("SalesOff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SalesGrp {
            get {
                return this.salesGrpField;
            }
            set {
                this.salesGrpField = value;
                this.RaisePropertyChanged("SalesGrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string FromTime {
            get {
                return this.fromTimeField;
            }
            set {
                this.fromTimeField = value;
                this.RaisePropertyChanged("FromTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ToTime {
            get {
                return this.toTimeField;
            }
            set {
                this.toTimeField = value;
                this.RaisePropertyChanged("ToTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ResultExplanation {
            get {
                return this.resultExplanationField;
            }
            set {
                this.resultExplanationField = value;
                this.RaisePropertyChanged("ResultExplanation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string FollowUpType {
            get {
                return this.followUpTypeField;
            }
            set {
                this.followUpTypeField = value;
                this.RaisePropertyChanged("FollowUpType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FollowUpDate {
            get {
                return this.followUpDateField;
            }
            set {
                this.followUpDateField = value;
                this.RaisePropertyChanged("FollowUpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ActivityComment {
            get {
                return this.activityCommentField;
            }
            set {
                this.activityCommentField = value;
                this.RaisePropertyChanged("ActivityComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Descrpt01 {
            get {
                return this.descrpt01Field;
            }
            set {
                this.descrpt01Field = value;
                this.RaisePropertyChanged("Descrpt01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Descrpt02 {
            get {
                return this.descrpt02Field;
            }
            set {
                this.descrpt02Field = value;
                this.RaisePropertyChanged("Descrpt02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Descrpt03 {
            get {
                return this.descrpt03Field;
            }
            set {
                this.descrpt03Field = value;
                this.RaisePropertyChanged("Descrpt03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Descrpt04 {
            get {
                return this.descrpt04Field;
            }
            set {
                this.descrpt04Field = value;
                this.RaisePropertyChanged("Descrpt04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Descrpt05 {
            get {
                return this.descrpt05Field;
            }
            set {
                this.descrpt05Field = value;
                this.RaisePropertyChanged("Descrpt05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Descrpt06 {
            get {
                return this.descrpt06Field;
            }
            set {
                this.descrpt06Field = value;
                this.RaisePropertyChanged("Descrpt06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Descrpt07 {
            get {
                return this.descrpt07Field;
            }
            set {
                this.descrpt07Field = value;
                this.RaisePropertyChanged("Descrpt07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Descrpt08 {
            get {
                return this.descrpt08Field;
            }
            set {
                this.descrpt08Field = value;
                this.RaisePropertyChanged("Descrpt08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Descrpt09 {
            get {
                return this.descrpt09Field;
            }
            set {
                this.descrpt09Field = value;
                this.RaisePropertyChanged("Descrpt09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Descrpt10 {
            get {
                return this.descrpt10Field;
            }
            set {
                this.descrpt10Field = value;
                this.RaisePropertyChanged("Descrpt10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string TxtKonse {
            get {
                return this.txtKonseField;
            }
            set {
                this.txtKonseField = value;
                this.RaisePropertyChanged("TxtKonse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string PartnRole {
            get {
                return this.partnRoleField;
            }
            set {
                this.partnRoleField = value;
                this.RaisePropertyChanged("PartnRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string PartnId {
            get {
                return this.partnIdField;
            }
            set {
                this.partnIdField = value;
                this.RaisePropertyChanged("PartnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string ContactRole {
            get {
                return this.contactRoleField;
            }
            set {
                this.contactRoleField = value;
                this.RaisePropertyChanged("ContactRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Langu {
            get {
                return this.languField;
            }
            set {
                this.languField = value;
                this.RaisePropertyChanged("Langu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string LanguIso {
            get {
                return this.languIsoField;
            }
            set {
                this.languIsoField = value;
                this.RaisePropertyChanged("LanguIso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class VbkaVbpa2kom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refobjecttypeField;
        
        private string refobjectkeyField;
        
        private string docNumberField;
        
        private string itmNumberField;
        
        private string countParvwField;
        
        private string partnRoleField;
        
        private string partnRoleOldField;
        
        private string partnIdField;
        
        private string partnIdOldField;
        
        private string addrNoField;
        
        private string persNoField;
        
        private string addrtypeField;
        
        private string addrOriginField;
        
        private string unloadPtField;
        
        private string calendarUpdateField;
        
        private string addrLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Refobjecttype {
            get {
                return this.refobjecttypeField;
            }
            set {
                this.refobjecttypeField = value;
                this.RaisePropertyChanged("Refobjecttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Refobjectkey {
            get {
                return this.refobjectkeyField;
            }
            set {
                this.refobjectkeyField = value;
                this.RaisePropertyChanged("Refobjectkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocNumber {
            get {
                return this.docNumberField;
            }
            set {
                this.docNumberField = value;
                this.RaisePropertyChanged("DocNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ItmNumber {
            get {
                return this.itmNumberField;
            }
            set {
                this.itmNumberField = value;
                this.RaisePropertyChanged("ItmNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CountParvw {
            get {
                return this.countParvwField;
            }
            set {
                this.countParvwField = value;
                this.RaisePropertyChanged("CountParvw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PartnRole {
            get {
                return this.partnRoleField;
            }
            set {
                this.partnRoleField = value;
                this.RaisePropertyChanged("PartnRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PartnRoleOld {
            get {
                return this.partnRoleOldField;
            }
            set {
                this.partnRoleOldField = value;
                this.RaisePropertyChanged("PartnRoleOld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PartnId {
            get {
                return this.partnIdField;
            }
            set {
                this.partnIdField = value;
                this.RaisePropertyChanged("PartnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PartnIdOld {
            get {
                return this.partnIdOldField;
            }
            set {
                this.partnIdOldField = value;
                this.RaisePropertyChanged("PartnIdOld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string AddrNo {
            get {
                return this.addrNoField;
            }
            set {
                this.addrNoField = value;
                this.RaisePropertyChanged("AddrNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PersNo {
            get {
                return this.persNoField;
            }
            set {
                this.persNoField = value;
                this.RaisePropertyChanged("PersNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Addrtype {
            get {
                return this.addrtypeField;
            }
            set {
                this.addrtypeField = value;
                this.RaisePropertyChanged("Addrtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AddrOrigin {
            get {
                return this.addrOriginField;
            }
            set {
                this.addrOriginField = value;
                this.RaisePropertyChanged("AddrOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string UnloadPt {
            get {
                return this.unloadPtField;
            }
            set {
                this.unloadPtField = value;
                this.RaisePropertyChanged("UnloadPt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CalendarUpdate {
            get {
                return this.calendarUpdateField;
            }
            set {
                this.calendarUpdateField = value;
                this.RaisePropertyChanged("CalendarUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string AddrLink {
            get {
                return this.addrLinkField;
            }
            set {
                this.addrLinkField = value;
                this.RaisePropertyChanged("AddrLink");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZIgnBpcontactGetlistResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VbkaVbpa2kom[] businesspartnerField;
        
        private Bus1037VbkakomCr[] generaldataField;
        
        private VbkaTlinekom[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VbkaVbpa2kom[] Businesspartner {
            get {
                return this.businesspartnerField;
            }
            set {
                this.businesspartnerField = value;
                this.RaisePropertyChanged("Businesspartner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bus1037VbkakomCr[] Generaldata {
            get {
                return this.generaldataField;
            }
            set {
                this.generaldataField = value;
                this.RaisePropertyChanged("Generaldata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VbkaTlinekom[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZIgnBpcontactGetlistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlist ZIgnBpcontactGetlist;
        
        public ZIgnBpcontactGetlistRequest() {
        }
        
        public ZIgnBpcontactGetlistRequest(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlist ZIgnBpcontactGetlist) {
            this.ZIgnBpcontactGetlist = ZIgnBpcontactGetlist;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZIgnBpcontactGetlistResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse ZIgnBpcontactGetlistResponse;
        
        public ZIgnBpcontactGetlistResponse1() {
        }
        
        public ZIgnBpcontactGetlistResponse1(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse ZIgnBpcontactGetlistResponse) {
            this.ZIgnBpcontactGetlistResponse = ZIgnBpcontactGetlistResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZIGNMOBILESALESACTIVITYChannel : SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZIGNMOBILESALESACTIVITYClient : System.ServiceModel.ClientBase<SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY>, SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY {
        
        public ZIGNMOBILESALESACTIVITYClient() {
        }
        
        public ZIGNMOBILESALESACTIVITYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZIGNMOBILESALESACTIVITYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZIGNMOBILESALESACTIVITYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZIGNMOBILESALESACTIVITYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1 SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY.ZIgnBpcontactGetlist(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest request) {
            return base.Channel.ZIgnBpcontactGetlist(request);
        }
        
        public SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse ZIgnBpcontactGetlist(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlist ZIgnBpcontactGetlist1) {
            SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest inValue = new SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest();
            inValue.ZIgnBpcontactGetlist = ZIgnBpcontactGetlist1;
            SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1 retVal = ((SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY)(this)).ZIgnBpcontactGetlist(inValue);
            return retVal.ZIgnBpcontactGetlistResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1> SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY.ZIgnBpcontactGetlistAsync(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest request) {
            return base.Channel.ZIgnBpcontactGetlistAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistResponse1> ZIgnBpcontactGetlistAsync(SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlist ZIgnBpcontactGetlist) {
            SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest inValue = new SAP.CRM.Gateway.SAPServiceReference.ZIgnBpcontactGetlistRequest();
            inValue.ZIgnBpcontactGetlist = ZIgnBpcontactGetlist;
            return ((SAP.CRM.Gateway.SAPServiceReference.ZIGNMOBILESALESACTIVITY)(this)).ZIgnBpcontactGetlistAsync(inValue);
        }
    }
}
