// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SAP.CRM.Core.BL;
using SAP.CRM.Core.BL.Managers;

namespace SAP.CRM.MT
{
	public partial class ActivitySeachTableViewController : UITableViewController
	{
		public ActivitySeachTableViewController (IntPtr handle) : base (handle)
		{
		}
				
		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			ActivitySearchSettings activitySearchSettings;

			// Get data for view
			activitySearchSettings = ActivityManager.GetActivitySearchSettings();
			if(activitySearchSettings == null) 
			{
				// Create new if not exists
				activitySearchSettings = new ActivitySearchSettings();
				ActivityManager.SaveActivitySearchSettings(activitySearchSettings);
			}
			// Prepare controls for output
			if(activitySearchSettings.MyActivities == "") MyActivityCell.Accessory = UITableViewCellAccessory.None;
			else MyActivityCell.Accessory = UITableViewCellAccessory.Checkmark;

			if(activitySearchSettings.MyCustomers == "") MyCustomersCell.Accessory = UITableViewCellAccessory.None;
			else MyCustomersCell.Accessory = UITableViewCellAccessory.Checkmark;

			this.TableView.Delegate = new ActivitySearchTableViewDelegate(activitySearchSettings);

			// Information message to user changing the search criteria
			string detailMessage = "Modifying the seach criteria will trigger a full refresh of activity data";
			new UIAlertView("Information", detailMessage, null, "OK", null).Show();
		}
	}
	

	public class ActivitySearchTableViewDelegate : UITableViewDelegate
	{
		private ActivitySearchSettings activitySearchSettings;

		public ActivitySearchTableViewDelegate(){}

		public ActivitySearchTableViewDelegate(ActivitySearchSettings settings)
		{
			activitySearchSettings = settings;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			if(indexPath.Row == 0 && indexPath.Section == 0)
			{
				if(activitySearchSettings.MyActivities ==  "")
				{
					activitySearchSettings.MyActivities = "X";
					tableView.CellAt (indexPath).Accessory = UITableViewCellAccessory.Checkmark;
				}
				else
				{
					activitySearchSettings.MyActivities = "";
					tableView.CellAt (indexPath).Accessory = UITableViewCellAccessory.None;
				}
				ActivityManager.SaveActivitySearchSettings(activitySearchSettings);
				tableView.DeselectRow (indexPath, true);
			}

			if(indexPath.Row == 1 && indexPath.Section == 0)
			{
				if(activitySearchSettings.MyCustomers ==  "")
				{
					activitySearchSettings.MyCustomers = "X";
					tableView.CellAt (indexPath).Accessory = UITableViewCellAccessory.Checkmark;
				}
				else
				{
					activitySearchSettings.MyCustomers = "";
					tableView.CellAt (indexPath).Accessory = UITableViewCellAccessory.None;
				}
				ActivityManager.SaveActivitySearchSettings(activitySearchSettings);
				tableView.DeselectRow (indexPath, true);
			}

		}
	}

}
