// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SAP.CRM.Core.BL;
using System.Collections.Generic;
using SAP.CRM.Core.BL.Managers;
using SAP.CRM.Core.DAL;

namespace SAP.CRM.MT
{
	public partial class ActivityTableViewController : UITableViewController
	{
		private ApplicationState appState;
		private Activity activity;
		LoadingOverlay loadingOverlay;

		public ActivityTableViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

			// Get data for view 
			activity = ActivityManager.GetActivity (ApplicationState.CurrentActivity);
			if (activity == null) {
				// Prompt error and go back to previous screen
			}


			 
        }
	}
}
