// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SAP.CRM.MT
{
	public partial class CustomActivityCell : UITableViewCell
	{

         // accessor properties to the outlets non-designer class 
        public MonoTouch.UIKit.UILabel Title 
        { 
            get { return TitleLabel; }
            set { TitleLabel = value; }
        }

        public MonoTouch.UIKit.UILabel SubTitle1
        {
            get { return SubTitle1Label; }
            set { SubTitle1Label = value; }
        }

        public MonoTouch.UIKit.UILabel SubTitle2
        {
            get { return SubTitle2Label; }
            set { SubTitle2Label = value; }
        }

		public CustomActivityCell (IntPtr handle) : base (handle)
		{
		}
	}
}
