// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SAP.CRM.MT
{
	public partial class SortGroupTableViewController : UITableViewController
	{
		public SortGroupTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
