// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using SAP.CRM.Core.BL;
using SAP.CRM.Core.BL.Managers;

namespace SAP.CRM.MT
{
	public partial class StatusSelectionTableViewController : UITableViewController
	{
		private ActivitySearchSettings settings;

		public StatusSelectionTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

		    settings = ActivityManager.GetActivitySearchSettings();
			
			TableView.Source = new StatusSelectionTableViewSource(settings);

			this.TableView.ReloadData();
		}
	}
	
	public class StatusSelectionTableViewSource : UITableViewSource
	{
		// declare vars
		protected ActivitySearchSettings searchSettings; 

		public StatusSelectionTableViewSource(ActivitySearchSettings settings)
		{
			searchSettings = settings;
		}


		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			//tableView.CellAt(indexPath).Accessory = UITableViewCellAccessory.Checkmark;
			new UIAlertView("Row Selected", "Test", null, "OK", null).Show();
			tableView.DeselectRow(indexPath, true);
		}

		#region implemented abstract members of UITableViewSource

		public override int RowsInSection (UITableView tableview, int section)
		{
			return tableview.NumberOfRowsInSection(section);
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			// request a recycled cell to save memory
			//UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
			return tableView.CellAt(indexPath);
		}

		#endregion


	}
}

